[package]
name = "mybtree"
version = "0.1.0"
edition = "2024"

[dependencies]
moka = { version = "0.12.10", features = ["sync"] }
rkyv = "0.8.14"

[dev-dependencies]
rand = "0.9.2"
tempfile = "3.24.0"
